# Квоты отбора файлов по исходному расширению (orig_ext).
# Значения трактуются как доли и должны суммироваться в 1.0.
orig_ext_quotas:
  gzip: 0.15 
  tar: 0.15
  rar: 0.15
  png: 0.10
  gif: 0.10
  bin: 0.10
  dll: 0.10
  apk: 0.05
  epub: 0.05
  oxps: 0.05


# Квоты алгоритмов аугментации.
# Значения трактуются как доли внутри sampled_df и должны суммироваться в 1.0.
algorithm_quotas:
  header-only: 0.5
  intermittent: 0.5
